---
- name: Set Redpanda RPM
  ansible.builtin.set_fact:
    # resolves stable vs unstable
    rp_standard_rpm_actuals: "{{ is_using_unstable | bool | ternary(rpm_standard_unstable_download_urls, rpm_standard_download_urls) }}"
    rp_noarch_rpm_actuals: "{{ is_using_unstable | bool | ternary(rpm_noarch_unstable_download_urls, rpm_noarch_download_urls) }}"
    rp_source_rpm_actuals: "{{ is_using_unstable | bool | ternary(rpm_source_unstable_download_urls, rpm_source_download_urls) }}"
  tags:
    - airgap-tarball-install

- name: Download Redpanda RPMs (standard) to local machine
  ansible.builtin.get_url:
    url: "{{ item.value }}"
    dest: "{{ download_directory }}/{{ item.key }}__standard.rpm"
    mode: '0644'
  loop: "{{ rp_standard_rpm_actuals | dict2items }}"
  delegate_to: localhost
  tags:
    - airgap-tarball-install

- name: Download Redpanda RPMs (noarch) to local machine
  ansible.builtin.get_url:
    url: "{{ item.value }}"
    dest: "{{ download_directory }}/{{ item.key }}__noarch.rpm"
    mode: '0644'
  loop: "{{ rp_noarch_rpm_actuals | dict2items }}"
  delegate_to: localhost
  tags:
    - airgap-tarball-install

- name: Download Redpanda RPMs (source) to local machine
  ansible.builtin.get_url:
    url: "{{ item.value }}"
    dest: "{{ download_directory }}/{{ item.key }}__source.rpm"
    mode: '0644'
  loop: "{{ rp_source_rpm_actuals | dict2items }}"
  delegate_to: localhost
  tags:
    - airgap-tarball-install

- name: Create tarball of Redpanda RPMs
  community.general.archive:
    path: "{{ download_directory }}/redpanda*__*.rpm"
    dest: "{{ download_directory }}/redpanda_rpms.tar.gz"
    format: gz
    remove: true
    mode: '0644'
  delegate_to: localhost
  tags:
    - airgap-tarball-install
