---
- name: Set fact for package name
  ansible.builtin.set_fact:
    redpanda_package_name: "redpanda{{ '' if redpanda_version=='latest' else ('=' if ansible_os_family == 'Debian' else '-') + redpanda_version }}"

- name: Set fact for redpanda-tuner package name
  ansible.builtin.set_fact:
    redpanda_tuner_package_name: "redpanda-tuner{{ '' if redpanda_version=='latest' else ('=' if ansible_os_family == 'Debian' else '-') + redpanda_version }}"

- name: Set fact for rpk package name
  ansible.builtin.set_fact:
    redpanda_rpk_package_name: "redpanda-rpk{{ '' if redpanda_version=='latest' else ('=' if ansible_os_family == 'Debian' else '-') + redpanda_version }}"

- name: Set fact for redpanda fips package name
  ansible.builtin.set_fact:
    redpanda_fips_package_name: "redpanda-fips{{ '' if redpanda_version=='latest' else ('=' if ansible_os_family == 'Debian' else '-') + redpanda_version }}"

- name: Set fact for rpk fips package name
  ansible.builtin.set_fact:
    redpanda_rpk_fips_package_name: "redpanda-rpk-fips{{ '' if redpanda_version=='latest' else ('=' if ansible_os_family == 'Debian' else '-') + redpanda_version }}"

#
# NOTE: Ordering matters here because of the package dependency chain.
#       DO NOT REORDER THESE INSTALLS -- THIS IS A HACK
#
# If you change the package ordering so that redpanda installs before redpanda-fips
# you will drag in the wrong rpk package and this will subsequently cause the fips
# package installs to fail. 
#

- name: check FIPS mode
  ansible.builtin.include_tasks: fips-assert.yml
  when: 
   - enable_fips | default(false) | bool
  
- name: Install redpanda-fips from repository
  ansible.builtin.package:
    name:
      - "{{ redpanda_fips_package_name }}"
    state: "{{ redpanda_install_status }}"
    update_cache: true
  register: package_result
  when:
   - enable_fips | default(false) | bool

- name: Install redpanda-rpk-fips from repository
  ansible.builtin.package:
    name:
      - "{{ redpanda_rpk_fips_package_name }}"
    state: "{{ redpanda_install_status }}"
    update_cache: true
  register: package_result
  when:
   - enable_fips | default(false) | bool

- name: Install redpanda from repository
  ansible.builtin.package:
    name:
      - "{{ redpanda_package_name }}"
    state: "{{ redpanda_install_status }}"
    update_cache: true
  register: package_result

- name: Install redpanda-tuner from repository
  ansible.builtin.package:
    name:
      - "{{ redpanda_tuner_package_name }}"
    state: "{{ redpanda_install_status }}"
    update_cache: true
  register: package_result



# when enable_fips is set, we have to ensure we don't install the non-FIPS
# version of rpk, as the redpanda-rpk and redpanda-rpk-fips packages conflict 
# and are mutually exclusive.
- name: Install redpanda-rpk from repository
  ansible.builtin.package:
    name:
      - "{{ redpanda_rpk_package_name }}"
    state: "{{ redpanda_install_status }}"
    update_cache: true
  register: package_result
  when:
   - enable_fips == false

- name: Set data dir file perms
  ansible.builtin.file:
    path: "{{ redpanda_data_directory }}"
    owner: redpanda
    group: redpanda
