- name: Check if RP exists
  ansible.builtin.stat:
    path: "/usr/bin/redpanda"
  register: rp_exists_check

- name: Get version from file
  ansible.builtin.command:
    cmd: "/usr/bin/redpanda --version"
  register: rp_ver_output
  when: rp_exists_check.stat.exists

- name: redpanda_version is post packaging split or not
  ansible.builtin.set_fact:
    is_post_split: "{{ redpanda_version == 'latest' or redpanda_version >= '24.2' }}"

- name: Check if redpanda_version is set to latest
  ansible.builtin.set_fact:
    needs_update: true
  when: redpanda_version == "latest"

- name: Compare version if redpanda_version is not set to latest
  ansible.builtin.set_fact:
    needs_update: "{{ (redpanda_version.replace('v', '').split('-')[0] | string ) is version((rp_ver_output.stdout.replace('v', '').split('-')[0] | string), '>') }}"
  when:
    - rp_exists_check.stat.exists
    - redpanda_version != "latest"

- name: Copy Redpanda RPMs tarball to host
  ansible.builtin.copy:
    src: "{{ airgap_copy_src }}/redpanda_rpms.tar.gz"
    dest: "{{ airgap_copy_dest }}/redpanda_rpms.tar.gz"
    mode: '0644'
  tags:
    - airgap-tarball-install
  when:
   - (needs_update | default(false)) or not rp_exists_check.stat.exists

- name: Unpack Redpanda RPMs on host
  ansible.builtin.unarchive:
    src: "{{ airgap_copy_dest }}/redpanda_rpms.tar.gz"
    dest: "{{ airgap_copy_dest }}"
  tags:
    - airgap-tarball-install
  when:
    - (needs_update | default(false)) or not rp_exists_check.stat.exists

- name: Install Redpanda RPMs (pre package split)
  ansible.builtin.shell: "rpm -Uvh --force {{ airgap_copy_dest }}/*.rpm"
  register: rpm_result
  failed_when: rpm_result.rc != 2 and rpm_result.rc != 0
  become: true
  tags:
    - airgap-tarball-install
  when:
    - (needs_update | default(false)) or not rp_exists_check.stat.exists
    - not is_post_split

- name: Install Redpanda RPMs (post package split)
  ansible.builtin.shell: "rpm -Uvh --force {{ airgap_copy_dest }}/{{item}}*__*.rpm"
  register: rpm_result
  failed_when: rpm_result.rc != 2 and rpm_result.rc != 0
  become: true
  tags:
    - airgap-tarball-install
  when:
    - (needs_update | default(false)) or not rp_exists_check.stat.exists
    - is_post_split
  loop:
    - redpanda-rpk
    - redpanda-tuner
    - redpanda

